### ISSUE TITLE
mod GenerateAPictureStoryUsingOnlySpeech.java to use OCI speech as option to whisper

### ISSUE THREAD

**Issue by paulparkinson** [oracle-devrel/oracle-ai-for-sustainable-dev#2]

**Comment by paulparkinson** [comment]
Miles and David
this also exists in https://github.com/oracle-devrel/oracle-health-ai-open-source for breast, lung, etc. cancer models

**Comment by paulparkinson** [comment]
this is in Java
David is doing the objectstore part and Miles the OCI speech part/call

**Comment by dangond** [comment]
Sending object to file storage is ready for GenerateAPictureStoryUsingOnlySpeech.java. Just need to coordinate with Miles for OCI bucket credentials to fill in. 

Same is true for the[ file in Oracle-health-ai-open-source repo (MedicalTranscriptionsController.java) 
](https://github.com/oracle-devrel/oracle-health-ai-open-source/issues/3)
